# Generated by Django 5.0.4 on 2024-05-06 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Maxsulot nomi', max_length=255),
            preserve_default=False,
        ),
    ]
